### ISSUE TITLE
ConfigParser.NoSectionError

### ISSUE THREAD

**Issue by t0mekk** [nickpesce/L.I.T.#1]
I cant make it work. 
Tried on Pi3B Xubuntu and Raspbian (latest versions).
Im getting errors trying run web_server.py.
![2017-06-28_22-37-50](https://user-images.githubusercontent.com/17167438/27663696-eb8ff2b6-5c63-11e7-949d-542c84324d7f.png)
Probably its something with "commands" module, which is depreciated since Python 2.6 (I'm on 2.7).
https://docs.python.org/2/library/commands.html

**Comment by nickpesce** [comment]
Hey! I believe the problem was just that the default config file didn't follow the most recent format. I updated it and the error that you posted should be fixed. I can't test it right now because I don't have any lights plugged in, so can you tell me if everything works? Thanks!

**Comment by t0mekk** [comment]
web_server.py now works, thanks :]
but there's another problem, with generate.py - I'm getting error that "Range" is not defined (or smt),
What I've done - in commands.py added `ranges = []`, in generate.py `api_dict_format` replaced with `api_list_format`, it helped, but api-ai refuses to read generated jsons. 

If its needed Ill create next issue later (and upload some screens).

**Comment by nickpesce** [comment]
I seem to have neglected generate.py after making changes to the range system. i updated it to work with simple sections of lights, but not zones, which are groups of sections. I will do that when I get a setup to test on.

**Comment by nickpesce** [comment]
Does everything work for you now?

**Comment by t0mekk** [comment]
yup, now it's working.  issue resolved :) thank you for help.

I had problem with uploading jsons also (had to copy-paste manually its contents, and del some commas and brackets to make it work).

I'm wraping my head around api-ap now.
