### ISSUE TITLE
Problems after the system restart of raspberry pi

### ISSUE THREAD

**Issue by Mdxin** [nickpesce/L.I.T.#3]
I Restart my raspberry pi and it will only light up three beads.

I restart my raspberry pi(4B) after it will only light up three beads.
It can only be fix it after use: `sudo systemctl restart litd`

This is my `ranges.json`
```
{
    "sections" : [
        {"name": "range 1", "size": 10, "adapter": "ws2812"},
        {"name": "range 2", "size": 10, "adapter": "ws2812"},
        {"name": "range 3", "size": 10, "adapter": "ws2812"}
    ],
    "adapters": [
        {"name": "ws2812", "type": "ws2812", "pin": 18, "size": 30}
    ],
    "zones" : [
        {"name": "all", "sections": ["range 1", "range 2", "range 3"]},
        {"name": "one and two", "sections": ["range 1", "range 2"]}
    ],
    "default" : "all"
}
```

**Comment by nickpesce** [comment]
Can you confirm that the lit daemon is running after your rpi is restarted? Immediately after restarting, what is the output of `sudo systemctl status litd`? When a signal is not actively being sent to the leds, noise in the wires can cause leds to turn on randomly.
